envName:
  $[envName]
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: $[env.profile]
  application:
    name: fim-server
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        max-wait: 10000
sharding:
  jdbc:
    datasource:
      names: db0
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/fim?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: root.123
      props:
        sql:
          show: true
    config:
      sharding:
        tables:
          t_message:
            actual-data-nodes: db0.t_message_$->{1..2}
            table-strategy:
              inline:
                sharding-column: message_id
                algorithm-expression: t_message_$->{message_id%2 + 1}
          t_offline_message:
            actual-data-nodes: db0.t_offline_message_$->{1..2}
            table-strategy:
              inline:
                sharding-column: receiver_id
                algorithm-expression: t_message_$->{receiver_id%2 + 1}

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.yytxdy.fim.server.entity
server:
  port: $[server.port]
fim:
  nettyPort: $[nettyPort]
grpc:
  port: $[grpcPort]
